auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import SignupView, SigninView, ResetPasswordView, ChangePasswordView, profile

from .forms import LoginForm

app_name = "account"
urlpatterns = [
    path('register/', SignupView.as_view(), name='signup'),
    path('login/', SigninView.as_view(redirect_authenticated_user=True, template_name='user/login.html', authentication_form=LoginForm), name='signin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='signout'),
    path('profile/', profile, name='profile'),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

home/urls.py
from django.urls import path
from home import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "home"
urlpatterns = [
    path('', views.home, name='home'),
]

menu/urls.py
from django.contrib import admin

from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__reload__/', include('django_browser_reload.urls')),
    path('', include('home.urls')),
    path('auth/', include('auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib import messages
# from .models import Account


def home(request):
    messages.success(request, "Welcome!")
    return render(request, 'home.html')

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Menu</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'toastr/toastr.min.css' %}" media="all">
	<script type="text/javascript" src="{% static 'toastr/toastr.min.js' %}"></script>  
	{% tailwind_css %}
</head>

<body class="bg-white font-serif leading-normal tracking-normal">
	{% block content %}
	{% endblock content %}
</body>

</html>

templates/home.html
{% extends "base.html" %}
{% block title %} Menu-Home {% endblock title%}
{% block content %}
<div class="flex flex-col items-center justify-center bg-slate-100">
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' and user.username %}
    <script type=text/javascript>toastr.{{ message.tags }}('{{ message }} {{ user.username }}')</script>
    {% elif message.tags == 'info' %}
    <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
    {% elif message.tags == 'warning' %}
    <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
    {% elif message.tags == 'error' %}
    <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
    {% endif %}
    {% endfor %}
    {% endif %}
    <span class='font-sans text-center font-semibold text-[40px] mt-10'> Welcome,
        {{user.username|default:'Guest'}}</span>
    <div class="flex flex-row items-center gap-x-[10px] justify-center mt-4">
        <span class="text-[#212121] text-[18px] leading-[21px] font-normal">This is CRUD example site created by</span>
        <a href="http://github.com/oskar0112" target="_blank"
            class="text-[#F33F34] text-[18px] leading-[21px] font-normal border-b-2 border-red-400">Oskar</a>
    </div>
    <div class="flex flex-row items-center gap-40 mt-5 mb-5">
        {% if user.is_authenticated %}
        <a class="font-normal text-[20px] border-red-800 hover:border-b-2" href="{% url 'account:signout' %}">Sign
            Out</a>
        <span class="text-[#212121] text-[18px] leading-[21px] font-normal">Go to my
            <a class="font-normal text-[20px] text-red-600 hover:border-b-2"
                href="{% url 'account:profile' %}"><i>Profile</i></a>
        </span>
        {% else %}
        <a class="font-normal text-[20px] border-red-800 hover:border-b-2" href="{% url 'account:signin' %}">Sign in</a>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/side.html
{% load static %}

<div class="flex flex-1 bg-[#FFF5F5] items-center flex-col">
    <div class="flex flex-col text-center">
        <span class="font-semibold mt-[73px] text-[#212121] text-[40px]">Make more beautiful UI</span>
        <span class="text-[#F33F34] text-[40px]">Menu Effective</span>
    </div>
    <div class="mt-[30px]">
        <img src="{% static 'images/apple-iphone-13-mini-2021-medium 1.png' %}" alt="apple-iphone-13-mini-2021-medium 1"
            class="w-[372px] h-[750px]">
    </div>
    <div class="mt-[30px] gap-[13px] h-[20px]">

    </div>
</div>

templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center justify-center pt-[70px] p-[60px] bg-white">
        <span class='font-sans text-center font-semibold text-[40px] leading-[52px]'>Registrazione</span>
        <div class="flex flex-row items-center gap-x-[5px]">
            <span class="text-[#212121] text-[18px] leading-[21px] font-normal">Hai già un account?</span>
            <span class="text-[#F33F34] text-[18px] leading-[21px] font-normal">Accedi</span>
        </div>
        <form action="{% url " signup" %}" method="post">
            {% csrf_token %}
            <div class="mt-[30px] flex flex-col gap-y-[20px] w-full">

                <div class="flex flex-col gap-y-[10px]">
                    <span class="text-[#212121] font-semibold text-[18px]">Inserisci la tua mail:</span>
                    <input type="text" value="{{ account.mail }}"
                        class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                        placeholder="Mail">
                </div>

                <div class="flex flex-col gap-y-[10px]">
                    <span class="text-[#212121] font-semibold text-[18px]">Scegli la password:</span>
                    <input type="password" value="{{ account.password }}"
                        class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                        placeholder="Password">
                </div>

                <div class="flex flex-col gap-y-[10px]">
                    <span class="text-[#212121] font-semibold text-[18px]">Nome attività:</span>
                    <div class="relative flex flex-row items-center">
                        <input type="text" id="activityInput" value="{{ account.co_name }}"
                            class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] disabled:bg-[#EFEFEF] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                            placeholder="Cerca su Google Maps">
                        <img src="/static/images/google-map.png" alt="google-map" id="googlemapImg"
                            class="w-[17px] h-[24px] absolute right-[20px]">
                    </div>
                </div>
                <div class="flex flex-row items-center gap-[4px]">
                    <input id="disableCheckbox" class="rounded-sm" type="checkbox">
                    <span class="text-[#737373]"> La mia attività non è su Google (o non riesco a trovarla al
                        momento)</span>
                </div>
                <div class="bg-[#FFF5F5] h-[86px] flex flex-col items-center justify-center">
                    <span class="text-[#212121]">Il link del tuo menu sarà:</span>
                    <span class="text-[#F33F34]">Il tuo link apparirà qua {{ account.logo_url }}</span>
                </div>
                <div class="flex flex-col gap-[10px]">
                    <div>
                        <span class="text-[#212121] text-[18px] font-normal leading-[23px]">Logo del tuo locale</span>
                        <span class="text-[#737373]">(puoi anche inserlo più avanti)</span>
                    </div>
                    <div
                        class="border-[#CCCCCC] border border-dashed h-[160px] flex flex-col items-center justify-center">
                        <img src="/static/images/default-upload.png" alt="default-upload"
                            class="w-[80px] h-[80px] p-[10px]">
                        <span class="text-[#737373] font-normal text-[18px]">Scegli i file che vuoi caricare dal tuo
                            computer o trascinali qua.</span>
                    </div>
                </div>
                <div class="flex flex-row items-center gap-[4px]">
                    <input class="rounded-sm" type="checkbox">
                    <span class="text-[#737373]">Accetto i </span>
                    <span class="text-[#F33F34]">Termini e Condizioni</span>
                </div>
                <button type="submit"
                    class="bg-[#EFEFEF] w-[115px] h-[57px] p-[10px] text-[#FFFFFF] rounded-[8px]">Registrati</button>

            </div>
        </form>
    </div>
    <div class="flex flex-1 bg-[#FFF5F5] items-center flex-col">
        <div class="flex flex-col text-center">
            <span class="font-semibold mt-[73px] text-[#212121] text-[40px]">Tanti ristoratori già usano</span>
            <span class="text-[#F33F34] text-[40px]">MenuEfficace</span>
        </div>
        <div class="mt-[30px]">
            <img src="/static/images/apple-iphone-13-mini-2021-medium 1.png" alt="apple-iphone-13-mini-2021-medium 1"
                class="w-[372px] h-[750px]">
        </div>
        <div class="mt-[30px] gap-[13px] h-[20px]">

        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var inputElement = document.getElementById("activityInput");
        var imgElement = document.getElementById("googlemapImg");
        var checkboxElement = document.getElementById("disableCheckbox");

        checkboxElement.addEventListener("change", function () {
            inputElement.disabled = checkboxElement.checked;
            if (checkboxElement.checked)
                googlemapImg.classList.add("opacity-20");
            else
                googlemapImg.classList.remove("opacity-20");
        });
    });
</script>
{% endblock content %}

templates/user/change_password.html
{% extends "base.html" %}
{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center p-[60px] bg-white">
        <span class='font-sans text-center font-semibold text-[40px] leading-[52px]'>Change Your Password</span>
        {% if user_form.errors %}
        <div class="flex flex-col items-center gap-y-[3px] mt-[20px]">
            {% for key, value in user_form.errors.items %}
            <span class="text-[#F33F34] text-[18px] leading-[21px] font-normal">{{ key }} {{ value }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mt-[30px] flex flex-col w-full">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex flex-col gap-y-[20px]">
                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Old Password:</span>
                        <input type="password" name="old_password" autocomplete="new-password"
                            class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                            required id="id_old_password" placeholder="Enter Old Password" />
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">New Password:</span>
                        <input type="password" name="new_password1" autocomplete="new-password"
                            class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                            required id="id_new_password1" placeholder="Enter New Password" />
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">New Password Confirmation:</span>
                        <input type="password" name="new_password2" autocomplete="new-password"
                            class="w-full h-[48px] border border-[#CCCCCC] rounded-[8px] bg-transparent focus:outline-none outline-none px-[15px] text-[#212121] text-[16px]"
                            required id="id_new_password2" placeholder="Confirm New Password" />
                    </div>

                    <div class="flex flex-row gap-x-[40px]">
                        <button type="submit" id="reset"
                            class="bg-slate-200 hover:bg-slate-300 w-[200px] h-[57px] p-[10px] text-slate-700 font-bold rounded-[8px] hover:text-[18px] duration-100">Update
                            Password</button>
                        <div class="items-center justify-center mt-4 text-[20px] leading-[21px] font-normal">
                            <span class="text-[#212121]">Go back to
                            </span>
                            <a href="{% url 'home:home' %}"
                                class="text-[#F33F34] underline-offset-1 border-red-400 border-b-2">Home</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include "side.html" %}
</div>
{% endblock content %}

templates/user/login.html
{% extends "base.html" %}

{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center p-[60px] bg-white">
        <span class='font-sans text-center font-semibold text-[40px] leading-[52px]'>Sign In</span>
        <div class="flex flex-row items-center gap-x-[5px] mt-[20px]">
            <span class="text-[#212121] text-[18px] leading-[21px] font-normal">This is created by </span>
            <span class="text-[#F33F34] text-[18px] leading-[21px] font-normal">Oskar</span>
        </div>
        <div class="mt-[30px] flex flex-col gap-y-[20px] w-full">
            <form method="POST">
                {% csrf_token %}
                <!-- {% if form.errors %}
                        {% for key, value in form.errors.items %}
                        <strong>{{ key }}{{ value }}</strong>
                        {% endfor %}
                </div>
                {% endif %} -->
                <div class="flex flex-col gap-y-[20px]">
                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Username</span>
                        {{ form.username }}
                        {% if form.errors.username %}
                        <strong class="text-red-700">{{ form.errors.username }}</strong>
                        {% endif %}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Password</span>
                        {{ form.password }}
                    </div>

                    <div class="flex flex-row gap-x-[20px] items-center">
                        {{ form.remember_me }}
                        <label> Remember me</label>
                    </div>

                    <div class="flex flex-row gap-x-[20px]">
                        <button type="submit"
                            class="bg-slate-200 hover:bg-slate-300 w-[115px] h-[57px] p-[10px] text-slate-700 font-bold rounded-[8px] hover:text-[18px] duration-100">Sign
                            In</button>
                        <div class="items-center justify-center mt-4 text-[20px] leading-[21px] font-normal">
                            <span class="text-[#212121]">Don't have an account yet?
                            </span>
                            <a href="{% url 'account:signup' %}"
                                class="text-[#F33F34] underline-offset-1 border-red-400 border-b-2">Sign up</a>
                        </div>
                        <div class="items-center justify-center mt-4 text-[16px] leading-[21px] font-normal hover:text-[18px] hover:text-slate-800 duration-150">
                            <a href="{% url 'account:password_reset' %}"><i>Forgot Password?</i></a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include "side.html" %}
</div>
{% endblock content %}

templates/user/logout.html
{% extends "base.html" %}
{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address.
        </p>
        <br>
        <hr><a href="{% url 'account:signin' %}" class="btn btn-primary">Sign in again</a>
    </div>
</div>
<div id="toast-default"
    class="flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
    role="alert">
    <div
        class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M15.147 15.085a7.159 7.159 0 0 1-6.189 3.307A6.713 6.713 0 0 1 3.1 15.444c-2.679-4.513.287-8.737.888-9.548A4.373 4.373 0 0 0 5 1.608c1.287.953 6.445 3.218 5.537 10.5 1.5-1.122 2.706-3.01 2.853-6.14 1.433 1.049 3.993 5.395 1.757 9.117Z" />
        </svg>
        <span class="sr-only">Fire icon</span>
    </div>
    <div class="ml-3 text-sm font-normal">Set yourself free.</div>
    <button type="button"
        class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
        data-dismiss-target="#toast-default" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
        </svg>
    </button>
</div>


{% endblock content %}

templates/user/password_reset.html
{% extends "base.html" %}
{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center p-[60px] bg-white">
        <span class='font-sans text-center font-semibold text-[40px] leading-[52px]'>Forgot Password?</span>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in form.errors.items %}
                <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        <div class="mt-[30px] flex flex-col w-full">
            <form method="POST">
                {% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <div id="form_errors">
                        {% for key, value in form.errors.items %}
                        <strong>{{ value }}</strong>
                        {% endfor %}
                    </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div class="flex flex-col gap-y-[20px]">

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Mail</span>
                        {{ form.email }}
                    </div>
                    <button type="submit"
                        class="bg-slate-200 hover:bg-slate-300 w-[115px] h-[57px] p-[10px] text-slate-700 font-bold rounded-[8px] hover:text-[18px] duration-100">Submit</button>

                    <div
                        class="flex flex-row gap-x-[40px] items-center justify-center mt-4 text-[20px] leading-[21px] font-normal">
                        <a href="{% url 'account:signup' %}" class="text-[#212121]">Create A New Account</a>
                        <a href="{% url 'account:signin' %}" class="text-[#212121]">Back To Login</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include "side.html" %}
</div>
{% endblock content %}

templates/user/password_reset_complete.html
{% extends "user/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

templates/user/profile.html
{% extends "base.html" %}
{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center p-[60px] bg-white">
        <img class="rounded-full" src="{{ user.profile.avatar.url }} " style="cursor: pointer;" />
        {% if user_form.errors %}
        <div class="flex flex-col items-center gap-y-[3px] mt-[20px]">
            {% for key, value in user_form.errors.items %}
            <span class="text-[#F33F34] text-[18px] leading-[21px] font-normal">{{ key }} {{ value }}</span>
            {% endfor %}
        </div>
        {% endif %}
        <div class="mt-[30px] flex flex-col w-full">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex flex-col gap-y-[20px]">
                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Username:</span>
                        {{ user_form.username }}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Email:</span>
                        {{ user_form.email }}
                    </div>

                    <div class="items-center justify-center mt-4 text-[16px] leading-[21px] font-normal">
                        <a href="{% url 'account:password_change' %}"><i
                                class="text-red-600 hover:text-[18px] duration-100">Change Password</i></a>
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Change Avatar:</span>
                        {{ profile_form.avatar }}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Bio:</span>
                        {{ profile_form.bio }}
                    </div>

                    <div class="flex flex-row gap-x-[40px]">
                        <button type="submit"
                            class="bg-slate-200 hover:bg-slate-300 w-[115px] h-[57px] p-[10px] text-slate-700 font-bold rounded-[8px] hover:text-[18px] duration-100">Save</button>
                        <div class="items-center justify-center mt-4 text-[20px] leading-[21px] font-normal">
                            <span class="text-[#212121]">Go back to
                            </span>
                            <a href="{% url 'home:home' %}"
                                class="text-[#F33F34] underline-offset-1 border-red-400 border-b-2">Home</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include "side.html" %}
</div>
{% endblock content %}

templates/user/register.html
{% extends "base.html" %}

{% block content %}
<div class="flex flex-row">
    <div class="w-[778px] flex flex-col items-center p-[60px] bg-white">
        <span class='font-sans text-center font-semibold text-[40px] leading-[52px]'>Sign Up</span>
        <div class="flex flex-row items-center gap-x-[5px] mt-[20px]">
            <span class="text-[#212121] text-[18px] leading-[21px] font-normal">This is created by </span>
            <span class="text-[#F33F34] text-[18px] leading-[21px] font-normal">Oskar</span>
        </div>
        <div class="mt-[30px] flex flex-col w-full">
            <form method="POST">
                {% csrf_token %}
                <div class="flex flex-col gap-y-[20px]">
                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Username</span>
                        {{ form.username }}
                        {% if form.errors.username %}
                        <strong class="text-red-700">{{ form.errors.username }}</strong>
                        {% endif %}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Mail</span>
                        {{ form.email }}
                        {% if form.errors.email %}
                        <strong class="text-red-700">{{ form.errors.email }}</strong>
                        {% endif %}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Password</span>
                        {{ form.password1 }}
                        {% if form.errors.password2 %}
                        <strong class="text-red-700">{{ form.errors.password2 }}</strong>
                        {% endif %}
                    </div>

                    <div class="flex flex-col gap-y-[10px]">
                        <span class="text-[#212121] font-semibold text-[18px]">Confirm Password</span>
                        {{ form.password2 }}
                    </div>

                    <div class="flex flex-row gap-x-[40px]">
                        <button type="submit"
                            class="bg-slate-200 hover:bg-slate-300 w-[115px] h-[57px] p-[10px] text-slate-700 font-bold rounded-[8px] hover:text-[18px] duration-100">Sign
                            Up</button>
                        <div class="items-center justify-center mt-4 text-[20px] leading-[21px] font-normal">
                            <span class="text-[#212121]">Have an account? Go to
                            </span>
                            <a href="{% url 'account:signin' %}"
                                class="text-[#F33F34] underline-offset-1 border-red-400 border-b-2">Sign in</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% include "side.html" %}
</div>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Menu</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
        {% block content %}
        {% endblock content %}
	</body>
</html>

theme/templates/signup.html
{% extends "base.html" %}

{% block content %}
    {#    <div class="container mx-auto">#}
    {#        <section class="flex items-center justify-center h-screen">#}
    {#            <h1 class="text-5xl">Django + Tailwind = ❤️</h1>#}
    {#        </section>#}
    {#    </div>#}
    <section class='bg-gray-800 text-white p-3 md:px-10 lg:px-20 xl:px-40 2xl:px-72'>Registrazione</section>
    <section>Hai già un account? Accedi</section>
    <section>
        <label>Inserisci la tua mail:</label>
        <input type="text" placeholder="Mail">
    </section>
    <section>
        <label>Scegli la password:</label>
        <input type="password" placeholder="Password">
    </section>
    <section>
        <section>
            <label>Nome attività:</label>
            <input type="text" placeholder="Cerca su Google Maps">
        </section>
        <section>
            <input type="checkbox" id="google" name="google">
            <label for="google">La mia attività non è su Google (o non riesco a trovarla al momento)</label>
        </section>
    </section>
    <section>
        <p>Il link del tuo menu sarà:</p>
        <p>Il tuo link apparirà qua</p>
    </section>
    <section>
        <p>
            <spin>Logo del tuo locale</spin>
            <spin>(puoi anche inserlo più avanti)</spin>
        </p>
        <section>
            <p>Scegli i file che vuoi caricare dal tuo computer o trascinali qua.</p>
        </section>
    </section>
    <section>
        <input type="checkbox" id="accept" name="accept">
        <label for="accept">Accetto i Termini e Condizioni</label>
    </section>
    <button>Registrati</button>
{% endblock content %}